services:
  - type: web
    name: pto-ppr
    env: node
    buildCommand: cd client && npm install && npm run build && cd ../server && npm install
    startCommand: node server/server.js
    rootDir: .
